[package]
name                = "taliyah"
version             = "0.7.0-alpha"
authors             = ["evieluvsrainbows"]
description         = "A Discord bot written in Rust with Serenity and Poise."
homepage            = "https://github.com/evieluvsrainbows/taliyah"
repository          = "https://github.com/evieluvsrainbows/taliyah.git"
keywords            = ["discord", "discord-api", "bot", "serenity"]
edition             = "2024"
license             = "MIT"
readme              = "README.md"
include             = ["src/**/*", "config.sample.toml", "Cargo.toml", "README.md"]

[profile.release]
opt-level           = 3
lto                 = true
codegen-units       = 1
panic               = "abort"
strip               = true

[dependencies]
anyhow              = "1.0.104"
chrono              = "0.4.45"
humantime           = "2.4.0"
itertools           = "0.15.0"
poise               = "0.7.0"
reqwest             = { version = "0.12.28", default-features = false, features = ["json", "multipart", "stream", "rustls-tls"]}
serenity            = "0.12.5"
serde               = { version = "1.0.229", features = ["derive"] }
serde_json          = "1.0.151"
tokio               = { version = "1.53.1", features = ["full"] }
toml                = "1.1.6"
tracing             = "0.1.44"
tracing-log         = "0.2.0"
tracing-subscriber  = { version = "0.3.23", features = ["env-filter"] }
